### ISSUE TITLE
Multiple file extensions under one description

### ISSUE THREAD

**Issue by TheBigFailure** [MrThearMan/filedialogs#4]
### I have read the docs thoroughly before making this feature request.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### Description

_Apologies, I understand that my actions do not strictly follow `CONTRIBUTING.md`. Please consider my request and implementation._

Parameter of `ext` from `filedialogues.open_file_dialogue` only allows one extension per description (`list[tuple[str, str]]`). Requesting maybe switch to format `list[tuple[str, tuple[str]]]`? This will allow multiple file extensions to be placed under one description.

Example usage:
```python
open_file_dialog(ext=[
    ("Video Files", ("mp4", "mkv", ...)),
    ("All Files", ("*",)),
])
```

### Motivation

Currently, the below
![image](https://user-images.githubusercontent.com/90491805/232673708-fa72f398-02ec-4e96-bae6-279524b38ee2.png)
is not possible. `open_file_dialogue` dialogue will simply not show the filetypes. If this feature is implemented, users of the module can specify specific types of files based off categories rather than only having All Files or One Extension Type. This will be very useful! Thanks in advance!

### Would you like to solve this issue yourself with a pull request?

Yes, waiting to create pull request. Code is indeed finished and functional. Please let me know when I can open my pull request.

**Comment by TheBigFailure** [comment]
@MrThearMan Please let me know when I can open my pull request. My code is working; I've tested it. I've referenced this issue, as listed above.

**Comment by MrThearMan** [comment]
Thanks for your feature request! And no worries on the formalities, I copied the contributing template I used for my other projects to this one, and not everything applies here, like automated testing.

Anyways, this is a great addition and I'm happy to merge it. I went over the pull request and added some comments, we can continue the conversation there!
